url: "https://blog.liquidbytes.net"
baseURL: "https://blog.liquidbytes.net"
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: friendly
pygmentsUseClasses: true
name: "Liquid Bytes"
title: "Liquid Bytes - Software Engineering & Management Blog"
languageCode: "en-us"
theme: liquidbytes
copyright: "You are free to share"
publishDir: "../lastzero.github.io"
outputFormats:
  html:
    minify: true
  json:
    minify: true

minificationOptions:
  KeepConditionalComments: true
  KeepEndTags: false

params:
  twitter:
    - card: "summary_large_image"
    - creator: "@lastzero"
    - image: "https://blog.liquidbytes.net/img/thumbnail.jpg"
  image: "https://blog.liquidbytes.net/img/thumbnail.jpg"
  thumbnail: "https://blog.liquidbytes.net/img/thumbnail.jpg"
  author: Michael Mayer
  description: "Michael learned coding on an Atari 1040 ST and started his first open-source projects in the 90s. He has more than 20 years of experience in leading teams and building Web applications."
  footer_menus:
    - name: "Social"
      menu: "profiles"
    - name: "Projects"
      menu: "projects"
  authorname: Nicholas Whittier
  authorlink: http://imperialwicket.com
  authortwitter: nw_iw
  authorgithub: imperialwicket
  authorbio: Some dude.
  authorimage: faces.jpg
  inc:
    # Blog Information
    title:        "Liquid Bytes"
    subtitle:     "Software Engineering & Management Blog"
    cover_image:  "https://blog.liquidbytes.net/img/thumbnail.jpg"
    logo:         "https://blog.liquidbytes.net/img/logo.png"

    # Company information
    company:      Liquid Bytes
    url:          "https://blog.liquidbytes.net"
    #    facebook:
    github:       lastzero
    twitter:      lastzero
    #    gplus:        ''
    about_link:   "https://blog.liquidbytes.net"

    # Sharing settings
    sharing:
      twitter:    https://twitter.com/lastzero
      facebook:   false
      gplus:      false
      hn:         false
    google_font: 'Droid+Sans:400,700'

menu:
  main:
    - Name: "Blog"
      URL: "/"
      Weight: 10
    - Name: "Open Source"
      URL: "/opensource/"
      Weight: 20
    - Name: "About"
      URL: "/about/"
      Weight: 30
    - Name: "Contact"
      URL: "/contact/"
      Weight: 40
  profiles:
    - Name: "GitHub"
      URL: "https://github.com/lastzero"
      Weight: 10
    - Name: "Twitter"
      Icon: "fab fa-twitter"
      URL: "https://twitter.com/lastzero"
      Weight: 20
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/lastzero/"
      Weight: 30
  projects:
    - Name: "PhotoPrism"
      URL: "https://photoprism.org/"
      Weight: 10
    - Name: "TweetHog"
      URL: "https://github.com/lastzero/tweethog"
      Weight: 20
    - Name: "Symlex"
      URL: "https://github.com/symlex"
      Weight: 30
